name: Build Windows MSI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Install WiX
        run: dotnet tool install wix

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: >-
            gcc
            make
            pkg-config
            cmake
            meson
            ninja
            git
            glib2-devel
            perl
            perl-XML-LibXML

      - name: Install XML::FromPerl manually
        shell: msys2 {0}
        run: |
          curl -L -o XML-FromPerl.tar.gz https://cpan.metacpan.org/authors/id/S/SA/SALVA/XML-FromPerl-0.01.tar.gz
          tar -xzf XML-FromPerl.tar.gz
          cd XML-FromPerl-0.01
          perl Makefile.PL
          make
          make install

      - name: Clone and build libslirp v4.9.0
        shell: msys2 {0}
        run: |
          git clone --branch v4.9.0 --depth 1 https://gitlab.freedesktop.org/slirp/libslirp.git
          cd libslirp
          meson build
          ninja -C build install

      - name: Configure the build with CMake
        shell: msys2 {0}
        run: |
          mkdir -p build
          cd build
          cmake .. -G "Unix Makefiles"

      - name: Compile the application using make
        shell: msys2 {0}
        run: |
          cd build
          make -j$(nproc)

      - name: Run Perl script to generate MSI
        shell: msys2 {0}
        run: |
          export PATH=$PATH:"/c/wix"
          perl scripts/mkmsi.pl  # Adjust path as needed

      - name: Find and upload MSI
        run: |
          $msi_file = Get-ChildItem -Path . -Filter "*.msi" -Recurse | Select-Object -ExpandProperty FullName
          echo "Found MSI: $msi_file"
          echo "MSI_PATH=$msi_file" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: MSI-Package
          path: ${{ env.MSI_PATH }}
